#!/bin/sh
for file in /etc/my_init.d/*; do 
if [ ${foo:0:1} == "_" ]; then
  exec $file &
else
  "$file" 
  te=$?
  if [ $te -ne 0 ]; then
    echo "file: $file errorcode:$te"
    exit $te
  fi
fi
done
exit 0
